const mockForecastResponse = {
  location: {
    name: "Latitude",
    region: "Sarawak",
    country: "Malaisie",
    lat: 1.58,
    lon: 110.4,
    tz_id: "Asia/Kuching",
    localtime_epoch: 1724577153,
    localtime: "2024-08-25 17:12",
  },
  current: {
    last_updated_epoch: 1724576400,
    last_updated: "2024-08-25 17:00",
    temp_c: 31.1,
    temp_f: 88.0,
    is_day: 1,
    condition: {
      text: "Partly cloudy",
      icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
      code: 1003,
    },
    wind_mph: 4.3,
    wind_kph: 6.8,
    wind_degree: 190,
    wind_dir: "S",
    pressure_mb: 1008.0,
    pressure_in: 29.77,
    precip_mm: 1.62,
    precip_in: 0.06,
    humidity: 66,
    cloud: 50,
    feelslike_c: 44.4,
    feelslike_f: 111.8,
    windchill_c: 26.9,
    windchill_f: 80.4,
    heatindex_c: 31.6,
    heatindex_f: 88.8,
    dewpoint_c: 25.4,
    dewpoint_f: 77.6,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 6.0,
    gust_mph: 8.7,
    gust_kph: 14.0,
  },
  forecast: {
    forecastday: [
      {
        date: "2024-08-25",
        date_epoch: 1724544000,
        day: {
          maxtemp_c: 29.8,
          maxtemp_f: 85.6,
          mintemp_c: 23.6,
          mintemp_f: 74.5,
          avgtemp_c: 25.5,
          avgtemp_f: 77.8,
          maxwind_mph: 4.0,
          maxwind_kph: 6.5,
          totalprecip_mm: 17.86,
          totalprecip_in: 0.7,
          totalsnow_cm: 0.0,
          avgvis_km: 8.4,
          avgvis_miles: 5.0,
          avghumidity: 90,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 90,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Moderate rain",
            icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
            code: 1189,
          },
          uv: 11.0,
        },
        astro: {
          sunrise: "06:36 AM",
          sunset: "06:45 PM",
          moonrise: "11:39 PM",
          moonset: "11:16 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: 65,
          is_moon_up: 1,
          is_sun_up: 1,
        },
        hour: [
          {
            time_epoch: 1724515200,
            time: "2024-08-25 00:00",
            temp_c: 24.3,
            temp_f: 75.7,
            is_day: 0,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/263.png",
              code: 1150,
            },
            wind_mph: 2.5,
            wind_kph: 4.0,
            wind_degree: 211,
            wind_dir: "SSW",
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.58,
            precip_in: 0.02,
            snow_cm: 0.0,
            humidity: 94,
            cloud: 53,
            feelslike_c: 26.9,
            feelslike_f: 80.5,
            windchill_c: 24.3,
            windchill_f: 75.7,
            heatindex_c: 26.9,
            heatindex_f: 80.5,
            dewpoint_c: 23.2,
            dewpoint_f: 73.8,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 5.0,
            vis_miles: 3.0,
            gust_mph: 4.8,
            gust_kph: 7.7,
            uv: 0,
          },
          {
            time_epoch: 1724518800,
            time: "2024-08-25 01:00",
            temp_c: 24.2,
            temp_f: 75.6,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 209,
            wind_dir: "SSW",
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.64,
            precip_in: 0.03,
            snow_cm: 0.0,
            humidity: 94,
            cloud: 51,
            feelslike_c: 26.8,
            feelslike_f: 80.3,
            windchill_c: 24.2,
            windchill_f: 75.6,
            heatindex_c: 26.8,
            heatindex_f: 80.3,
            dewpoint_c: 23.2,
            dewpoint_f: 73.7,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 0,
          },
          {
            time_epoch: 1724522400,
            time: "2024-08-25 02:00",
            temp_c: 24.1,
            temp_f: 75.3,
            is_day: 0,
            condition: {
              text: "Patchy light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/293.png",
              code: 1180,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 212,
            wind_dir: "SSW",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 1.15,
            precip_in: 0.05,
            snow_cm: 0.0,
            humidity: 95,
            cloud: 52,
            feelslike_c: 26.7,
            feelslike_f: 80.1,
            windchill_c: 24.1,
            windchill_f: 75.3,
            heatindex_c: 26.7,
            heatindex_f: 80.1,
            dewpoint_c: 23.3,
            dewpoint_f: 73.9,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 0,
          },
          {
            time_epoch: 1724526000,
            time: "2024-08-25 03:00",
            temp_c: 23.8,
            temp_f: 74.8,
            is_day: 0,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/263.png",
              code: 1150,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 225,
            wind_dir: "SW",
            pressure_mb: 1010.0,
            pressure_in: 29.81,
            precip_mm: 0.45,
            precip_in: 0.02,
            snow_cm: 0.0,
            humidity: 96,
            cloud: 88,
            feelslike_c: 26.4,
            feelslike_f: 79.5,
            windchill_c: 23.8,
            windchill_f: 74.8,
            heatindex_c: 26.4,
            heatindex_f: 79.5,
            dewpoint_c: 23.2,
            dewpoint_f: 73.8,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 5.0,
            vis_miles: 3.0,
            gust_mph: 5.8,
            gust_kph: 9.3,
            uv: 0,
          },
          {
            time_epoch: 1724529600,
            time: "2024-08-25 04:00",
            temp_c: 23.7,
            temp_f: 74.7,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 230,
            wind_dir: "SW",
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.2,
            precip_in: 0.01,
            snow_cm: 0.0,
            humidity: 96,
            cloud: 100,
            feelslike_c: 26.3,
            feelslike_f: 79.3,
            windchill_c: 23.7,
            windchill_f: 74.7,
            heatindex_c: 26.3,
            heatindex_f: 79.3,
            dewpoint_c: 23.0,
            dewpoint_f: 73.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 5.1,
            gust_kph: 8.2,
            uv: 0,
          },
          {
            time_epoch: 1724533200,
            time: "2024-08-25 05:00",
            temp_c: 23.6,
            temp_f: 74.5,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 198,
            wind_dir: "SSW",
            pressure_mb: 1010.0,
            pressure_in: 29.82,
            precip_mm: 0.2,
            precip_in: 0.01,
            snow_cm: 0.0,
            humidity: 96,
            cloud: 82,
            feelslike_c: 26.1,
            feelslike_f: 79.0,
            windchill_c: 23.6,
            windchill_f: 74.5,
            heatindex_c: 26.1,
            heatindex_f: 79.0,
            dewpoint_c: 22.9,
            dewpoint_f: 73.1,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 3.9,
            gust_kph: 6.2,
            uv: 0,
          },
          {
            time_epoch: 1724536800,
            time: "2024-08-25 06:00",
            temp_c: 23.7,
            temp_f: 74.6,
            is_day: 0,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/263.png",
              code: 1150,
            },
            wind_mph: 2.5,
            wind_kph: 4.0,
            wind_degree: 163,
            wind_dir: "SSE",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.24,
            precip_in: 0.01,
            snow_cm: 0.0,
            humidity: 95,
            cloud: 82,
            feelslike_c: 26.2,
            feelslike_f: 79.1,
            windchill_c: 23.7,
            windchill_f: 74.6,
            heatindex_c: 26.2,
            heatindex_f: 79.1,
            dewpoint_c: 22.8,
            dewpoint_f: 73.1,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 5.0,
            vis_miles: 3.0,
            gust_mph: 4.3,
            gust_kph: 6.8,
            uv: 0,
          },
          {
            time_epoch: 1724540400,
            time: "2024-08-25 07:00",
            temp_c: 23.7,
            temp_f: 74.6,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 151,
            wind_dir: "SSE",
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.42,
            precip_in: 0.02,
            snow_cm: 0.0,
            humidity: 95,
            cloud: 74,
            feelslike_c: 26.2,
            feelslike_f: 79.1,
            windchill_c: 23.7,
            windchill_f: 74.6,
            heatindex_c: 26.2,
            heatindex_f: 79.1,
            dewpoint_c: 22.8,
            dewpoint_f: 73.0,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 4.6,
            gust_kph: 7.5,
            uv: 5.0,
          },
          {
            time_epoch: 1724544000,
            time: "2024-08-25 08:00",
            temp_c: 24.2,
            temp_f: 75.5,
            is_day: 1,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/day/143.png",
              code: 1030,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 134,
            wind_dir: "SE",
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.12,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 95,
            cloud: 83,
            feelslike_c: 26.8,
            feelslike_f: 80.3,
            windchill_c: 24.2,
            windchill_f: 75.5,
            heatindex_c: 26.8,
            heatindex_f: 80.3,
            dewpoint_c: 23.3,
            dewpoint_f: 73.9,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 4.3,
            gust_kph: 6.9,
            uv: 5.0,
          },
          {
            time_epoch: 1724547600,
            time: "2024-08-25 09:00",
            temp_c: 25.1,
            temp_f: 77.2,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 121,
            wind_dir: "ESE",
            pressure_mb: 1011.0,
            pressure_in: 29.87,
            precip_mm: 0.15,
            precip_in: 0.01,
            snow_cm: 0.0,
            humidity: 93,
            cloud: 75,
            feelslike_c: 28.2,
            feelslike_f: 82.8,
            windchill_c: 25.1,
            windchill_f: 77.2,
            heatindex_c: 28.2,
            heatindex_f: 82.8,
            dewpoint_c: 23.9,
            dewpoint_f: 75.0,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 6.0,
          },
          {
            time_epoch: 1724551200,
            time: "2024-08-25 10:00",
            temp_c: 26.3,
            temp_f: 79.3,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 115,
            wind_dir: "ESE",
            pressure_mb: 1012.0,
            pressure_in: 29.87,
            precip_mm: 0.13,
            precip_in: 0.01,
            snow_cm: 0.0,
            humidity: 88,
            cloud: 74,
            feelslike_c: 29.8,
            feelslike_f: 85.7,
            windchill_c: 26.3,
            windchill_f: 79.3,
            heatindex_c: 29.8,
            heatindex_f: 85.7,
            dewpoint_c: 24.2,
            dewpoint_f: 75.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.1,
            gust_kph: 8.2,
            uv: 6.0,
          },
          {
            time_epoch: 1724554800,
            time: "2024-08-25 11:00",
            temp_c: 27.5,
            temp_f: 81.5,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 132,
            wind_dir: "SE",
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.08,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 81,
            cloud: 81,
            feelslike_c: 31.4,
            feelslike_f: 88.5,
            windchill_c: 27.5,
            windchill_f: 81.5,
            heatindex_c: 31.4,
            heatindex_f: 88.5,
            dewpoint_c: 23.9,
            dewpoint_f: 75.0,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.0,
            gust_kph: 8.1,
            uv: 6.0,
          },
          {
            time_epoch: 1724558400,
            time: "2024-08-25 12:00",
            temp_c: 28.1,
            temp_f: 82.6,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 140,
            wind_dir: "SE",
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.82,
            precip_in: 0.03,
            snow_cm: 0.0,
            humidity: 77,
            cloud: 81,
            feelslike_c: 32.0,
            feelslike_f: 89.6,
            windchill_c: 28.1,
            windchill_f: 82.6,
            heatindex_c: 32.0,
            heatindex_f: 89.6,
            dewpoint_c: 23.6,
            dewpoint_f: 74.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.3,
            gust_kph: 8.5,
            uv: 6.0,
          },
          {
            time_epoch: 1724562000,
            time: "2024-08-25 13:00",
            temp_c: 28.3,
            temp_f: 83.0,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 142,
            wind_dir: "SE",
            pressure_mb: 1010.0,
            pressure_in: 29.82,
            precip_mm: 0.41,
            precip_in: 0.02,
            snow_cm: 0.0,
            humidity: 75,
            cloud: 73,
            feelslike_c: 32.3,
            feelslike_f: 90.1,
            windchill_c: 28.3,
            windchill_f: 83.0,
            heatindex_c: 32.3,
            heatindex_f: 90.1,
            dewpoint_c: 23.6,
            dewpoint_f: 74.4,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.0,
            gust_kph: 8.0,
            uv: 6.0,
          },
          {
            time_epoch: 1724565600,
            time: "2024-08-25 14:00",
            temp_c: 29.8,
            temp_f: 85.6,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 116,
            wind_dir: "ESE",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.42,
            precip_in: 0.02,
            snow_cm: 0.0,
            humidity: 69,
            cloud: 87,
            feelslike_c: 34.3,
            feelslike_f: 93.7,
            windchill_c: 29.8,
            windchill_f: 85.6,
            heatindex_c: 34.3,
            heatindex_f: 93.7,
            dewpoint_c: 23.5,
            dewpoint_f: 74.3,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 2.3,
            gust_kph: 3.7,
            uv: 6.0,
          },
          {
            time_epoch: 1724569200,
            time: "2024-08-25 15:00",
            temp_c: 28.6,
            temp_f: 83.4,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 2.5,
            wind_kph: 4.0,
            wind_degree: 60,
            wind_dir: "ENE",
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 1.06,
            precip_in: 0.04,
            snow_cm: 0.0,
            humidity: 80,
            cloud: 70,
            feelslike_c: 33.7,
            feelslike_f: 92.6,
            windchill_c: 28.6,
            windchill_f: 83.4,
            heatindex_c: 33.7,
            heatindex_f: 92.6,
            dewpoint_c: 24.8,
            dewpoint_f: 76.7,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.3,
            gust_kph: 5.3,
            uv: 6.0,
          },
          {
            time_epoch: 1724572800,
            time: "2024-08-25 16:00",
            temp_c: 27.7,
            temp_f: 81.9,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 52,
            wind_dir: "NE",
            pressure_mb: 1008.0,
            pressure_in: 29.76,
            precip_mm: 1.25,
            precip_in: 0.05,
            snow_cm: 0.0,
            humidity: 87,
            cloud: 75,
            feelslike_c: 32.9,
            feelslike_f: 91.2,
            windchill_c: 27.7,
            windchill_f: 81.9,
            heatindex_c: 32.9,
            heatindex_f: 91.2,
            dewpoint_c: 25.4,
            dewpoint_f: 77.7,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 6.0,
          },
          {
            time_epoch: 1724576400,
            time: "2024-08-25 17:00",
            temp_c: 31.1,
            temp_f: 88.0,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 190,
            wind_dir: "S",
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 1.62,
            precip_in: 0.06,
            snow_cm: 0.0,
            humidity: 66,
            cloud: 50,
            feelslike_c: 31.6,
            feelslike_f: 88.8,
            windchill_c: 26.9,
            windchill_f: 80.4,
            heatindex_c: 31.6,
            heatindex_f: 88.8,
            dewpoint_c: 25.4,
            dewpoint_f: 77.6,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.7,
            gust_kph: 14.0,
            uv: 6.0,
          },
          {
            time_epoch: 1724580000,
            time: "2024-08-25 18:00",
            temp_c: 26.3,
            temp_f: 79.4,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 347,
            wind_dir: "NNW",
            pressure_mb: 1008.0,
            pressure_in: 29.78,
            precip_mm: 1.1,
            precip_in: 0.04,
            snow_cm: 0.0,
            humidity: 92,
            cloud: 71,
            feelslike_c: 30.4,
            feelslike_f: 86.8,
            windchill_c: 26.3,
            windchill_f: 79.4,
            heatindex_c: 30.4,
            heatindex_f: 86.8,
            dewpoint_c: 24.9,
            dewpoint_f: 76.9,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.2,
            gust_kph: 5.2,
            uv: 6.0,
          },
          {
            time_epoch: 1724583600,
            time: "2024-08-25 19:00",
            temp_c: 24.7,
            temp_f: 76.5,
            is_day: 0,
            condition: {
              text: "Moderate or heavy rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/356.png",
              code: 1243,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 338,
            wind_dir: "NNW",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 2.65,
            precip_in: 0.1,
            snow_cm: 0.0,
            humidity: 93,
            cloud: 51,
            feelslike_c: 27.6,
            feelslike_f: 81.6,
            windchill_c: 24.8,
            windchill_f: 76.6,
            heatindex_c: 27.6,
            heatindex_f: 81.6,
            dewpoint_c: 23.5,
            dewpoint_f: 74.4,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7.0,
            vis_miles: 4.0,
            gust_mph: 3.5,
            gust_kph: 5.6,
            uv: 0,
          },
          {
            time_epoch: 1724587200,
            time: "2024-08-25 20:00",
            temp_c: 24.2,
            temp_f: 75.5,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 328,
            wind_dir: "NNW",
            pressure_mb: 1010.0,
            pressure_in: 29.82,
            precip_mm: 2.13,
            precip_in: 0.08,
            snow_cm: 0.0,
            humidity: 94,
            cloud: 83,
            feelslike_c: 26.8,
            feelslike_f: 80.2,
            windchill_c: 24.2,
            windchill_f: 75.5,
            heatindex_c: 26.8,
            heatindex_f: 80.2,
            dewpoint_c: 23.1,
            dewpoint_f: 73.6,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.2,
            gust_kph: 5.2,
            uv: 0,
          },
          {
            time_epoch: 1724590800,
            time: "2024-08-25 21:00",
            temp_c: 24.1,
            temp_f: 75.4,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 300,
            wind_dir: "WNW",
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 1.03,
            precip_in: 0.04,
            snow_cm: 0.0,
            humidity: 94,
            cloud: 75,
            feelslike_c: 26.7,
            feelslike_f: 80.0,
            windchill_c: 24.1,
            windchill_f: 75.4,
            heatindex_c: 26.7,
            heatindex_f: 80.0,
            dewpoint_c: 23.1,
            dewpoint_f: 73.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.0,
            gust_kph: 4.8,
            uv: 0,
          },
          {
            time_epoch: 1724594400,
            time: "2024-08-25 22:00",
            temp_c: 24.1,
            temp_f: 75.4,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 284,
            wind_dir: "WNW",
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.57,
            precip_in: 0.02,
            snow_cm: 0.0,
            humidity: 94,
            cloud: 73,
            feelslike_c: 26.7,
            feelslike_f: 80.0,
            windchill_c: 24.1,
            windchill_f: 75.4,
            heatindex_c: 26.7,
            heatindex_f: 80.0,
            dewpoint_c: 23.1,
            dewpoint_f: 73.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.5,
            gust_kph: 4.1,
            uv: 0,
          },
          {
            time_epoch: 1724598000,
            time: "2024-08-25 23:00",
            temp_c: 24.1,
            temp_f: 75.3,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 2.0,
            wind_kph: 3.2,
            wind_degree: 252,
            wind_dir: "WSW",
            pressure_mb: 1012.0,
            pressure_in: 29.87,
            precip_mm: 0.42,
            precip_in: 0.02,
            snow_cm: 0.0,
            humidity: 94,
            cloud: 79,
            feelslike_c: 26.6,
            feelslike_f: 79.9,
            windchill_c: 24.1,
            windchill_f: 75.3,
            heatindex_c: 26.6,
            heatindex_f: 79.9,
            dewpoint_c: 23.0,
            dewpoint_f: 73.3,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.8,
            gust_kph: 6.0,
            uv: 0,
          },
        ],
      },
    ],
  },
};

export default mockForecastResponse;
